server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CAP-CLOUD-CONFIG-SERVER
  sleuth:
    sampler:
      percentage: 1.0
  session:
    redis:
      flush-mode: on-save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.
    store-type: redis
  redis:
    jedis:
      pool:
        max-wait: 5000
        max-Idle: 50
        min-Idle: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# spring boot actuator
info:
  app:
    name: com.iisigroup.cap.app.CAP
    description: Cap by Spring Boot Application
    version: 5.0.1

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,info,monitor/hystrix.stream
management:
  endpoints:
    web.exposure.include: "*"
    health.sensitive: false
    shutdown.enabled: true
  endpoint.health.show-details: ALWAYS
endpoints.shutdown.enabled: true

security.oauth2.resource.filter-order: 3

# eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8001/eureka,http://localhost:8003/eureka

logging:
  level:
    ROOT: DEBUG
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG
    org:
      hibernate.type: WARN

#swaggerConfig:
  #apiVersion: ${project.version}
